main: dev.ryben.scavengerhunt.Main
name: ${project.name}
author: redraskal
version: ${project.version}
api-version: 1.13
description: "A Halloween scavenger hunt plugin based off of a popular network!"
website: "https://github.com/JediMasterSoda/GhostScavengerHunt"
load: POSTWORLD
softdepend: [PlaceholderAPI, Multiverse-Core]

commands:
  ghostskull:
    description: "Gives yourself a Ghost skull to add to the Scavenger Hunt."
  skulls:
    description: "Displays the amount of skulls you have collected."

permissions:
  ghostskull.*:
    children:
      ghostskull.spawn: true
      ghostskull.break: true
    default: default
  ghostskull.spawn:
    default: op
  ghostskull.break:
    default: op
